### ISSUE TITLE
filter aligned sequences

### ISSUE THREAD

**Issue by thedam** [mikerobeson/make_SILVA_db#1]
hey,
in the point 6, can we filter sequences like this?
```
egrep '^>' SILVA_seqs_polyfilt_lenfilt.fasta | sed 's/>//g' > ids_to_keep.txt
awk '{print "grep -m 1 -A 1 "$1" SILVA_align_seqs.fasta >> SILVA_align_seqs_polyfilt_lenfilt.fasta" }' ids_to_keep.txt | source /dev/stdin 
```
instead of using Qiime1? :)

**Comment by thedam** [comment]
noo it's super slow ;/

**Comment by mikerobeson** [comment]
Hey it was worth a shot @thedam! I plan to add more easy-to-use scripts to avoid the bioawk / awk commands. Mainly because I am quite rusty with sed / awk and perl one-liners. :-)

**Comment by thedam** [comment]
ok, here is better:
1) `docker pull sglim2/qiime-1.9.1`
2) `docker run -it --rm -v $PWD:$PWD sglim2/qiime-1.9.1 filter_fasta.py -s $PWD/ids_to_keep.txt -f $PWD/SILVA_align_seqs.fasta -o $PWD/SILVA_align_seqs_polyfilt_lenfilt.fasta`
:)
