### ISSUE TITLE
Silva 138 vs Silva 132 taxonomy

### ISSUE THREAD

**Issue by thedam** [mikerobeson/make_SILVA_db#2]
Hey Mike,
Silva_132 downloaded from https://www.arb-silva.de/no_cache/download/archive/qiime/ has namings like this:
```
KF494428.1.1396	D_0__Bacteria;D_1__Epsilonbacteraeota;D_2__Campylobacteria;D_3__Campylobacterales;D_4__Thiovulaceae;D_5__Sulfuricurvum;D_6__Sulfuricurvum sp. EW1
AF506248.1.1375	D_0__Bacteria;D_1__Cyanobacteria;D_2__Oxyphotobacteria;D_3__Nostocales;D_4__Nostocaceae;D_5__Nostoc PCC-73102;D_6__Nostoc sp. 'Nephroma expallidum cyanobiont 23'
```
and names in SILVA_138_Taxonomy.txt are like this:
```
KF494428.1.1396	d__Bacteria; p__Campilobacterota; c__Campylobacteria; o__Campylobacterales; f__Sulfurimonadaceae; g__Sulfuricurvum; s__Sulfuricurvum_sp._EW1
AF506248.1.1375	d__Bacteria; p__Cyanobacteria; c__Cyanobacteriia; o__Cyanobacteriales; f__Nostocaceae; g__Nostoc_PCC-73102; s__Nostoc_sp._Nephroma_expallidum_cyanobiont_23
```
I'm not experienced yet, but won't it affect the analysis? Shouldn't the 138's names by also like: D_0__, D_1__, D_2__ ?

**Comment by mikerobeson** [comment]
He @thedam, The prefixes to each of the ranks are not important. In fact we are trying to update the way we structure the SILVA reference files for QIIME, that is, make it more "GreenGenes-like". For some more detail about the "D_X__" see [this](https://forum.qiime2.org/t/why-all-taxonomic-levels-on-barplot-have-d-letter/9239/4).
