### ISSUE TITLE
Step 7 

### ISSUE THREAD

**Issue by limeng849** [mikerobeson/make_SILVA_db#3]
I'm trying to follow the pipeline to map our primers(519-905) to the short alignment. However, when walking to the mafft alignment step, It doesn't work. It occurs a bug that Unknown option:  --mapout. The version of mafft I used is MAFFT v7.123b. By the way, I wonder where can I find the 
emp_primers.fasta.map file? 

Please help me, thanks a lot...

**Comment by mikerobeson** [comment]
Hi there! I am using MAFFT (ver 7.310) that ships with QIIME 2 (ver 2020.2). I just retested the command and it works. The error implies that your version of mafft does not have this option. Assuming you are using QIIME 2, you can forgo the alignment extraction strategy I outlined, and import the unaligned sequences and taxonomy into QIIME 2 and continue from [here](https://docs.qiime2.org/2020.2/tutorials/feature-classifier/#extract-reference-reads). The `emp_primers.fasta.map` is output from mafft as per my note.
